#!/usr/bin/ruby
require_relative 'lib/load'

groups = EvDed::load_and_transform(File.join(__dir__,'annotation_and_grouping.yaml'))

puts "Groups, Sensor and number data points:"
groups.each do |k,sensors|
  puts "  #{k}"
  sensors.each do |k,series|
    puts "    #{k}: #{series.length}"
  end
end

puts "\nStep 3: ..."

stime = '2022-07-19 10:02:57.22 +0200'
print "\nSearching for '#{stime}' in vgr/current_state: "
puts groups['vgr']['current_state'].find(stime)

# pp data
